<div class="desktop-only">
    <div class="banner">


<div id="slider1_container" style="display: none; position: relative; margin: 0 auto; top: 0px; left: 0px; right:0; width: 1300px; height: 270px; overflow: hidden;">
            <!-- Loading Screen -->
            <div u="loading" style="position: absolute; top: 0px; left: 0px; height:270px;">
                <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;
                top: 0px; left: 0px; width: 100%; height: 100%;">
                </div>
                <div style="position: absolute; display: block; background: url(<?php echo $sk['config']['theme_url']; ?>/images/loader.gif) no-repeat center center;
                top: 0px; left: 0px; width: 100%; height: 100%;">
                </div>
            </div>
            <!-- Slides Container -->
            <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1300px; height: 270px; overflow: hidden;">
                <div>
                    <img u="image" src="<?php echo $sk['config']['theme_url']; ?>/images/banner/red.jpg" />
                </div>
                <div>
                    <img u="image" src="<?php echo $sk['config']['theme_url']; ?>/images/banner/purple.jpg" />
                </div>
                <div>
                    <img u="image" src="<?php echo $sk['config']['theme_url']; ?>/images/banner/blue.jpg" />
                </div>
            </div>

            <!-- Bullet Navigator Skin Begin -->
            <style>
                /* jssor slider bullet navigator skin 21 css */
                /*
                .jssorb21 div           (normal)
                .jssorb21 div:hover     (normal mouseover)
                .jssorb21 .av           (active)
                .jssorb21 .av:hover     (active mouseover)
                .jssorb21 .dn           (mousedown)
                */
				#slider1_container {
					width: 100% !important;
				}
				
                .jssorb21 div, .jssorb21 div:hover, .jssorb21 .av {
                    background: url(<?php echo $sk['config']['theme_url']; ?>/images/b21.png) no-repeat;
                    overflow: hidden;
                    cursor: pointer;
                }

                .jssorb21 div {
                    background-position: -5px -5px;
                }

                    .jssorb21 div:hover, .jssorb21 .av:hover {
                        background-position: -35px -5px;
                    }

                .jssorb21 .av {
                    background-position: -65px -5px;
                }

                .jssorb21 .dn, .jssorb21 .dn:hover {
                    background-position: -95px -5px;
                }
            </style>
            <!-- bullet navigator container -->
            <div u="navigator" class="jssorb21" style="position: absolute; bottom: 0; left: 6px;">
                <!-- bullet navigator item prototype -->
                <div u="prototype" style="POSITION: absolute; WIDTH: 19px; HEIGHT: 19px; text-align:center; line-height:19px; color:White; font-size:12px;"></div>
            </div>
            <!-- Bullet Navigator Skin End -->
            <!-- Arrow Navigator Skin Begin -->
            <style>
                /* jssor slider arrow navigator skin 21 css */
                /*
                .jssora21l              (normal)
                .jssora21r              (normal)
                .jssora21l:hover        (normal mouseover)
                .jssora21r:hover        (normal mouseover)
                .jssora21ldn            (mousedown)
                .jssora21rdn            (mousedown)
                */
                .jssora21l, .jssora21r, .jssora21ldn, .jssora21rdn {
                    position: absolute;
                    cursor: pointer;
                    display: block;
                    background: url(<?php echo $sk['config']['theme_url']; ?>/images/a21.png) center center no-repeat;
                    overflow: hidden;
                }

                .jssora21l {
                    background-position: -3px -33px;
                }
				 .jssora21l:hover {
                    background-position: -123px -33px;
                }
                .jssora21r {
                    background-position: -195px -33px;
                }
				 .jssora21r:hover {
                    background-position: -315px -33px;
                }

                .jssora21ldn {
                    background-position: -243px -33px;
                }

                .jssora21rdn {
                    background-position: -315px -33px;
                }
            </style>
            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora21l" style="width: 55px; height: 55px; top: 123px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora21r" style="width: 55px; height: 55px; top: 123px; right: 8px">
            </span>
            <!-- Arrow Navigator Skin End -->
         
        </div>



    </div>

    <div>
        <h3>Recent Posts</h3>
        <div class="stories-container">
            <div class="stories-wrapper">
            <div class="slider6">
                <?php
                $stories = FA_getStories_recent();
                //var_dump($stories);die();
                if (is_array($stories) && count($stories) > 0) {

                    foreach($stories as $sk['story']) {?>
                    <div class="slide">
                        <?php echo FA_getPage('story/content-home'); ?>
                        </div>
                        <?php
                    }
                }
                ?>
                </div>
            </div>

        </div>
    </div>

    <div class="clearfix"></div>
    <div class="clearfix"></div>
    
    <div>
        <h3>Most Liked Posts</h3>
        <div class="stories-container">
            <div class="stories-wrapper">
                <?php
                $stories = FA_getStories_most_like();
                //var_dump($stories);die();
                if (is_array($stories) && count($stories) > 0) {

                    foreach($stories as $sk['story']) {
                        echo FA_getPage('story/content-home');
                    }
                }
                ?>
            </div>

        </div>
    </div>

</div>
<!--<div class="float-right span35">
    <?php
/*    if (isset($_GET['tab2']) && $_GET['tab2'] == "password_reset") {
        
        if (isset($_GET['id']) && FA_isValidPasswordResetToken($_GET['id']) != false) {
    */?>
    <form class="welcome-form passwordreset-form" method="post">
        <div class="form-header">
            <?php /*echo $lang['reset_password_label']; */?>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="pr_password" placeholder="<?php /*echo $lang['new_password_label']; */?>" autocomplete="off">
            </div>
            <button class="submit-btn active">
                <i class="icon-signin progress-icon"></i> <?php /*echo $lang['reset']; */?>
            </button>
        </div>
        <input type="hidden" name="pr_token" value="<?php /*echo $_GET['id']; */?>">
    </form>
    <?php
/*        } else {
    */?>
    <div class="welcome-form">
        <div class="form-header">
            Oops!
        </div>
        <div class="post-message">Invalid token!</div>
    </div>
    <?php
/*        }
    } else {
    */?>
    <?php
/*    if (isset($_GET['tab2']) && $_GET['tab2'] == "forgot_password") {
    */?>
    <form class="welcome-form forgotpass-form" method="post">
        <div class="form-header">
            <div class="float-left">
                <?php /*echo $lang['forgot_password']; */?>?
            </div>
            <div class="float-right">
                <a href="<?php /*echo FA_smoothLink('index.php?tab1=welcome'); */?>"><?php /*echo $lang['log_in']; */?></a>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="forgotpass_id" value="<?php /*echo $lang['login_id_label']; */?>" placeholder="<?php /*echo $lang['login_id_label']; */?>" data-placeholder="<?php /*echo $lang['login_id_label']; */?>" autocomplete="off">
            </div>
            <button class="submit-btn active">
                <i class="icon-inbox progress-icon"></i> <?php /*echo $lang['reset_password_reset']; */?>
            </button>
        </div>
    </form>
    <?php
/*    } else {
    */?>
    <form class="welcome-form login-form" method="post">
        <div class="form-header">
            <div class="float-left">
                <?php /*echo $lang['log_in']; */?>
            </div>
            <div class="float-right">
                <a href="<?php /*echo FA_smoothLink('index.php?tab1=welcome&tab2=forgot_password'); */?>"><?php /*echo $lang['forgot_password']; */?>?</a>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="login_id" value="<?php /*echo $lang['login_id_label']; */?>" placeholder="<?php /*echo $lang['login_id_label']; */?>" data-placeholder="<?php /*echo $lang['login_id_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="password" name="login_password" placeholder="Password" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="checkbox" name="keep_logged_in" value="1"> Keep me logged in
            </div>
            
            <button class="submit-btn active"><i class="icon-signin progress-icon"></i> <?php /*echo $lang['log_in']; */?></button>
        </div>
    </form>
    <?php
/*    }
    */?>
    <form class="welcome-form signup-form" method="post">
        <div class="form-header"><?php /*echo $lang['sign_up_label']; */?></div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="name" placeholder="<?php /*echo $lang['fullname_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="text" name="username" placeholder="<?php /*echo $lang['username_label']; */?>" onkeyup="FA_checkUsername(this.value,0,'.check-username-result',false);" autocomplete="off">
                <div class="check-username-result"></div>
            </div>
            
            <div class="input-wrapper">
                <input type="password" name="password" placeholder="<?php /*echo $lang['password_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="text" name="email" placeholder="<?php /*echo $lang['email_label']; */?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <select name="gender">
                    <option value=""><?php /*echo $lang['gender_label']; */?></option>
                    <option value="male"><?php /*echo $lang['gender_male_label']; */?></option>
                    <option value="female"><?php /*echo $lang['gender_female_label']; */?></option>
                </select>
            </div>

            <?php
/*            if ($sk['config']['reg_req_birthday'] == true) {
            */?>
            <div class="input-wrapper">
                <select class="birth-date-select" name="birthday[0]" style="width: 48px;">
                    <?php
/*                    for ($i = 1; $i < 32; $i++) {
                        
                        if ($i == $sk['user']['birth']['date']) {
                            $option = '<option value="' . $i . '" selected>' . $i . '</option>';
                        } else {
                            $option = '<option value="' . $i . '">' . $i . '</option>';
                        }
                        
                        echo $option;
                    }
                    */?>
                </select>
                <select class="birth-month-select" name="birthday[1]" style="width: 98px;" onchange="FA_getMonthDays(this.value);">
                    <?php
/*                    foreach (FA_getMonths() as $month_number => $month_data) {
                        
                        if ($month_number == $sk['user']['birth']['month']) {
                            $option = '<option value="' . $month_number . '" selected>' . $month_data[1] . '</option>';
                        } else {
                            $option = '<option value="' . $month_number . '">' . $month_data[1] . '</option>';
                        }
                        
                        echo $option;
                    }
                    */?>
                </select>
                <select class="birth-year-select" name="birthday[2]" style="width: 65px;">
                    <?php
/*                    for ($i = date('Y')-100; $i < date('Y')-12; $i++) {
                        
                        if ($i == $sk['user']['birth']['year']) {
                            $option = '<option value="' . $i . '" selected>' . $i . '</option>';
                        } else {
                            $option = '<option value="' . $i . '">' . $i . '</option>';
                        }
                        
                    echo $option;
                    }
                    */?>
                </select>
            </div>
            <script>
            function FA_getMonthDays(month_number) {
                var month = new Array();
                month[1] = 31;
                month[2] = 28;
                month[3] = 31;
                month[4] = 30;
                month[5] = 31;
                month[6] = 30;
                month[7] = 31;
                month[8] = 31;
                month[9] = 30;
                month[10] = 31;
                month[11] = 30;
                month[12] = 31;
                $('.birth-date-select').html('');
                
                for (i=1; i<=month[month_number]; i++) {
                    $('.birth-date-select').append('<option value="'+ i +'">'+ i +'</option>');
                }
            }
            </script>
            <?php
/*            }
            
            if ($sk['config']['reg_req_currentcity'] == true) {
            */?>
            <div class="input-wrapper">
                <input type="text" name="current_city" placeholder="<?php /*echo $lang['location_label']; */?>" autocomplete="off">
            </div>
            <?php
/*            }
            
            if ($sk['config']['reg_req_hometown'] == true) {
            */?>
            <div class="input-wrapper">
                <input type="text" name="hometown" placeholder="<?php /*echo $lang['hometown_label']; */?>" autocomplete="off">
            </div>
            <?php
/*            }
            
            if ($sk['config']['reg_req_about'] == true) {
            */?>
            <div class="input-wrapper">
                <textarea name="about" placeholder="<?php /*echo $lang['about_label']; */?>" autocomplete="off"></textarea>
            </div>
            <?php
/*            }

            if ($sk['config']['captcha'] == true) {
            $captcha = FA_createCaptcha();
            */?>
            <div class="input-wrapper">
                <table border="0" width="100%" cellspacing="0" cellpadding="0">
                <tr>
                    <td width="85px" align="left" valign="middle">
                        <img class="captcha" src="<?php /*echo $sk['config']['site_url'] . '/' . $captcha['image']; */?>">
                    </td>
                    <td align="left" valign="middle">
                        <input type="text" value="<?php /*echo $lang['captcha_label']; */?>" placeholder="<?php /*echo $lang['captcha_label']; */?>" data-placeholder="<?php /*echo $lang['captcha_label']; */?>" autocomplete="off" data-copy-to=".register-captcha-input">
                        <input class="register-captcha-input" type="hidden" name="captcha">
                    </td>
                </tr>
                </table>
            </div>
            <?php /*} */?>
            
            <button class="submit-btn active"><i class="icon-angle-right progress-icon"></i> <?php /*echo $lang['sign_up_label'] ;*/?></button>
        </div>
    </form>
    <?php
/*    }
    */?>
    <div class="fb-button">
        <a href="<?php /*echo $sk['fb_login_url']; */?>">
            <i class="icon-facebook"></i>
            <span>Connect with Facebook</span>
        </a>
    </div>
</div>-->

<div class="float-clear"></div>

<script type="text/javascript" src="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery-2.1.0.js"></script>
<script type="text/javascript" src="<?php echo $sk['config']['theme_url']; ?>/javascript/jssor.slider.mini.js"></script>
<script type="text/javascript" src="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery.bxslider.js"></script>
<link rel="stylesheet" href="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery.bxslider.css" type="text/css" />
<script>
        jQuery(document).ready(function ($) {
			
			var width = $(window).width(), height = $(window).height();
			
			if ((width <= 1023)) {
			
			$('.slider6').bxSlider({
				slideWidth: 300,
				mode: 'vertical',
    			minSlides: 2,
    			slideMargin: 20
			});
			}
			else{
				$('.slider6').bxSlider({
				slideWidth: 300,
				minSlides: 2,
				maxSlides: 3,
				startSlide: 2,
				slideMargin: 20
			});
			}
			
            var options = {
                $FillMode: 2,                                       //[Optional] The way to fill image in slide, 0 stretch, 1 contain (keep aspect ratio and put all inside slide), 2 cover (keep aspect ratio and cover whole slide), 4 actual size, 5 contain for large image, actual size for small image, default value is 0
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $PauseOnHover: 1,                                   //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                $ArrowKeyNavigation: true,   			            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                $SlideEasing: $JssorEasing$.$EaseOutQuint,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
                $SlideDuration: 800,                               //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
                //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
                //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
                $SlideSpacing: 0, 					                //[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                $DragOrientation: 1,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
              
                $BulletNavigatorOptions: {                          //[Optional] Options to specify and enable navigator or not
                    $Class: $JssorBulletNavigator$,                 //[Required] Class to create navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 1,                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1
                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange items, default value is 1
                    $SpacingX: 8,                                   //[Optional] Horizontal space between each item in pixel, default value is 0
                    $SpacingY: 8,                                   //[Optional] Vertical space between each item in pixel, default value is 0
                    $Orientation: 1,                                //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
                    $Scale: false,                                  //Scales bullets navigator or not while slider scale
                },

                $ArrowNavigatorOptions: {                           //[Optional] Options to specify and enable arrow navigator or not
                    $Class: $JssorArrowNavigator$,                  //[Requried] Class to create arrow navigator instance
                    $ChanceToShow: 1,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $Steps: 1                                       //[Optional] Steps to go for each navigation request, default value is 1
                }
            };

            //Make the element 'slider1_container' visible before initialize jssor slider.
            $("#slider1_container").css("display", "block");
            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var bodyWidth = document.body.clientWidth;
                if (bodyWidth)
                    jssor_slider1.$ScaleWidth(Math.min(bodyWidth, 1920));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>