<div class="page-margin"></div>

<div class="float-left span59">
    <form class="login-form1 signup-form" method="post">
        <div class="form-header"><?php echo $lang['sign_up_label']; ?></div>
        <?php if(!empty($_SESSION['social_signUp_msg'])){?>
        <div class="post-message" style="display: block;"><?php echo $_SESSION['social_signUp_msg']?></div>
        <?php }?>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="name" placeholder="<?php echo $lang['fullname_label']; ?>" autocomplete="off">
            </div>

            <div class="input-wrapper">
                <input type="text" name="username" placeholder="<?php echo $lang['username_label']; ?>" onkeyup="FA_checkUsername(this.value,0,'.check-username-result',false);" autocomplete="off">
                <div class="check-username-result"></div>
            </div>

            <div class="input-wrapper">
                <input type="password" name="password" placeholder="<?php echo $lang['password_label']; ?>" autocomplete="off">
            </div>

            <div class="input-wrapper">
                <input type="text" name="email" placeholder="<?php echo $lang['email_label']; ?>" autocomplete="off">
            </div>

            <div class="input-wrapper">
                <select name="gender">
                    <option value=""><?php echo $lang['gender_label']; ?></option>
                    <option value="male"><?php echo $lang['gender_male_label']; ?></option>
                    <option value="female"><?php echo $lang['gender_female_label']; ?></option>
                </select>
            </div>

            <?php
            if ($sk['config']['reg_req_birthday'] == true) {
                ?>
                <div class="input-wrapper">
                    <select class="birth-date-select" name="birthday[0]" style="width: 48px;">
                        <?php
                        for ($i = 1; $i < 32; $i++) {

                            if ($i == $sk['user']['birth']['date']) {
                                $option = '<option value="' . $i . '" selected>' . $i . '</option>';
                            } else {
                                $option = '<option value="' . $i . '">' . $i . '</option>';
                            }

                            echo $option;
                        }
                        ?>
                    </select>
                    <select class="birth-month-select" name="birthday[1]" style="width: 98px;" onchange="FA_getMonthDays(this.value);">
                        <?php
                        foreach (FA_getMonths() as $month_number => $month_data) {

                            if ($month_number == $sk['user']['birth']['month']) {
                                $option = '<option value="' . $month_number . '" selected>' . $month_data[1] . '</option>';
                            } else {
                                $option = '<option value="' . $month_number . '">' . $month_data[1] . '</option>';
                            }

                            echo $option;
                        }
                        ?>
                    </select>
                    <select class="birth-year-select" name="birthday[2]" style="width: 65px;">
                        <?php
                        for ($i = date('Y')-100; $i < date('Y')-12; $i++) {

                            if ($i == $sk['user']['birth']['year']) {
                                $option = '<option value="' . $i . '" selected>' . $i . '</option>';
                            } else {
                                $option = '<option value="' . $i . '">' . $i . '</option>';
                            }

                            echo $option;
                        }
                        ?>
                    </select>
                </div>
                <script>
                    function FA_getMonthDays(month_number) {
                        var month = new Array();
                        month[1] = 31;
                        month[2] = 28;
                        month[3] = 31;
                        month[4] = 30;
                        month[5] = 31;
                        month[6] = 30;
                        month[7] = 31;
                        month[8] = 31;
                        month[9] = 30;
                        month[10] = 31;
                        month[11] = 30;
                        month[12] = 31;
                        $('.birth-date-select').html('');

                        for (i=1; i<=month[month_number]; i++) {
                            $('.birth-date-select').append('<option value="'+ i +'">'+ i +'</option>');
                        }
                    }
                </script>
            <?php
            }

            if ($sk['config']['reg_req_currentcity'] == true) {
                ?>
                <div class="input-wrapper">
                    <input type="text" name="current_city" placeholder="<?php echo $lang['location_label']; ?>" autocomplete="off">
                </div>
            <?php
            }

            if ($sk['config']['reg_req_hometown'] == true) {
                ?>
                <div class="input-wrapper">
                    <input type="text" name="hometown" placeholder="<?php echo $lang['hometown_label']; ?>" autocomplete="off">
                </div>
            <?php
            }

            if ($sk['config']['reg_req_about'] == true) {
                ?>
                <div class="input-wrapper">
                    <textarea name="about" placeholder="<?php echo $lang['about_label']; ?>" autocomplete="off"></textarea>
                </div>
            <?php
            }

            if ($sk['config']['captcha'] == true) {
                $captcha = FA_createCaptcha();
                ?>
                <div class="input-wrapper">
                    <table border="0" width="100%" cellspacing="0" cellpadding="0">
                        <tr>
                            <td width="85px" align="left" valign="middle">
                                <img class="captcha" src="<?php echo $sk['config']['site_url'] . '/' . $captcha['image']; ?>">
                            </td>
                            <td align="left" valign="middle">
                                <input type="text" value="<?php echo $lang['captcha_label']; ?>" placeholder="<?php echo $lang['captcha_label']; ?>" data-placeholder="<?php echo $lang['captcha_label']; ?>" autocomplete="off" data-copy-to=".register-captcha-input">
                                <input class="register-captcha-input" type="hidden" name="captcha">
                            </td>
                        </tr>
                    </table>
                </div>
            <?php } ?>

            <button class="submit-btn active"><i class="icon-angle-right progress-icon"></i><?php echo $lang['sign_up_label'] ;?></button>
            <div>
                        <div class="col-md-1 control">
                            <a href="/login.php?network=facebook" class="btn btn-social-icon btn-facebook">Facebook</a>
                        </div>
                        <div class="col-md-1 control">
                            <a href="/login.php?network=twitter" class="btn btn-social-icon btn-twitter">twitter</a>
                        </div>
                        <div class="col-md-1 control">
                            <a href="/login.php?network=linkedin" class="btn btn-social-icon btn-linkedin">linkedin</a>
                        </div>
                        <div class="col-md-1 control">
                            <a href="/login.php?network=google" class="btn btn-social-icon btn-google-plus">google-plus</i></a>
                        </div>
                        <div class="col-md-1 control">
                            <a href="/login.php?network=yahoo" class="btn btn-social-icon btn-yahoo">yahoo</a>
                        </div>
                        
                    </div>
        </div>
    </form>


</div>

<div class="float-right span40">
    <div class="list-wrapper">
        <div class="list-header">What is Lorem Ipsum?</div>
        
        <div class="list-column">
            <strong class="bold-500">What is Lorem Ipsum?</strong>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
        
        <div class="list-column">
            <strong class="bold-500">What is Lorem Ipsum?</strong>
            <br>
             Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
        
        <div class="list-column">
            <strong class="bold-500">What is Lorem Ipsum?</strong>
            <br>
             Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>
    </div>
</div>

<div class="float-clear"></div>
