<div class="page-margin"></div>

<div class="float-right span35">
    <?php
    if (isset($_GET['tab2']) && $_GET['tab2'] == "password_reset") {
        
        if (isset($_GET['id']) && FA_isValidPasswordResetToken($_GET['id']) != false) {
    ?>
    <form class="login-form1 passwordreset-form" method="post">
        <div class="form-header">
            <?php echo $lang['reset_password_label']; ?>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="pr_password" placeholder="<?php echo $lang['new_password_label']; ?>" autocomplete="off">
            </div>
            <button class="submit-btn active">
                <i class="icon-signin progress-icon"></i> <?php echo $lang['reset']; ?>
            </button>
        </div>
        <input type="hidden" name="pr_token" value="<?php echo $_GET['id']; ?>">
    </form>
    <?php
        } else {
    ?>
    <div class="login-form1">
        <div class="form-header">
            Oops!
        </div>
        <div class="post-message">Invalid token!</div>
    </div>
    <?php
        }
    } else {
    ?>
    <?php
    if (isset($_GET['tab2']) && $_GET['tab2'] == "forgot_password") {
    ?>
    <form class="login-form1 forgotpass-form" method="post">
        <div class="form-header">
            <div class="float-left">
                <?php echo $lang['forgot_password']; ?>?
            </div>
            <div class="float-right">
                <a href="<?php echo FA_smoothLink('index.php?tab1=login'); ?>"><?php echo $lang['log_in']; ?></a>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="forgotpass_id" value="<?php echo $lang['login_id_label']; ?>" placeholder="<?php echo $lang['login_id_label']; ?>" data-placeholder="<?php echo $lang['login_id_label']; ?>" autocomplete="off">
            </div>
            <button class="submit-btn active">
                <i class="icon-inbox progress-icon"></i> <?php echo $lang['reset_password_reset']; ?>
            </button>
        </div>
    </form>
    <?php
    } else {
    ?>
    <form class="login-form1 login-form" method="post">
        <div class="form-header">
            <div class="float-left">
                <?php echo $lang['log_in']; ?>
            </div>
            <div class="float-right">
                <a href="<?php echo FA_smoothLink('index.php?tab1=login&tab2=forgot_password'); ?>"><?php echo $lang['forgot_password']; ?>?</a>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="form-content">
            <div class="input-wrapper">
                <input type="text" name="login_id" value="<?php echo $lang['login_id_label']; ?>" placeholder="<?php echo $lang['login_id_label']; ?>" data-placeholder="<?php echo $lang['login_id_label']; ?>" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="password" name="login_password" placeholder="Password" autocomplete="off">
            </div>
            
            <div class="input-wrapper">
                <input type="checkbox" name="keep_logged_in" value="1"> Keep me logged in
            </div>
            
            <button class="submit-btn active"><i class="icon-signin progress-icon"></i> <?php echo $lang['log_in']; ?></button>
        </div>
    </form>
    <?php
    }
    ?>
        </div>

    <?php
    }
    ?>



<div class="float-clear"></div>
