<style type="text/css">

body.dragging, body.dragging * {
  cursor: move !important;
}

.dragged {
  position: absolute;
  opacity: 0.5;
  z-index: 2000;
}

ol.example li.placeholder {
  position: relative;
  /** More li styles **/
}
ol.example li.placeholder:before {
  position: absolute;
  /** Define arrowhead **/
}

</style>
<div class="page-margin"></div>
<ol class='example'>
  <li>First</li>
  <li>Second</li>
  <li>Third</li>
</ol>


<div class="float-left span59">
    <form class="create-group-form" method="post">
        <div class="form-container">
            <div class="form-header"><?php echo $lang['group_create_label']; ?></div>
            <div class="form-input-wrapper">
                <label class="float-left span20"><?php echo $lang['polls_name_label']; ?>:</label>
                
                <div class="input float-left span70">
                    <input type="text" value="" placeholder="<?php echo $lang['polls_name_label_plcaeholder']?>" data-placeholder="<?php echo $lang['group_name_textarea_label']; ?>" onkeyup="FA_generateUsername(this.value);" data-copy-to=".group-name-input">
                    
                    <input class="group-name-input" type="hidden" name="group_name">
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    <?php
                    echo $lang['about_label'];
                    ?>:
                </label>
                
                <div class="input float-left span70">
                    <textarea class="auto-grow-input" valign="top" name="group_about" placeholder="<?php echo $lang['group_description_textarea_label']; ?>" data-placeholder="<?php echo $lang['group_description_textarea_label']; ?>"><?php echo $lang['group_description_textarea_label']; ?></textarea>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    <?php echo $lang['privacy_label']; ?>:
                </label>
                
                <div class="input float-left span70">
                    <div style="margin-bottom: 15px;">
                        <input valign="top" type="radio" name="group_privacy" value="open">
                        <label><i class="icon-globe"></i> <?php echo $lang['open_group']; ?></label>
                        <div class="short-descr">
                            <?php echo $lang['open_group_description']; ?>.
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 15px;">
                        <input valign="top" type="radio" name="group_privacy" value="closed" checked>
                        <label><i class="icon-lock"></i> <?php echo $lang['closed_group']; ?></label>
                        <div class="short-descr">
                            <?php
                            echo $lang['closed_group_description'];
                            ?>.
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <input valign="top" type="radio" name="group_privacy" value="secret">
                        <label><i class="icon-shield"></i> <?php echo $lang['secret_group']; ?></label>
                        <div class="short-descr">
                            <?php
                            echo $lang['secret_group_description'];
                            ?>.
                        </div>
                    </div>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <button class="active">
                    <?php
                    echo $lang['group_create_label'];
                    ?>
                </button>
            </div>
        </div>
    </form>
</div>

<div class="float-right span40">
    <div class="list-wrapper">
        <div class="list-header"><?php echo $lang['group_intro_header']; ?></div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list1_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list1_description']; ?>
        </div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list2_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list2_description']; ?>
        </div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list3_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list3_description']; ?>
        </div>
    </div>
</div>
<div class="float-clear"></div>
<script src="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery-sortable.js"></script>
<script type="text/javascript">
$(function  () {
	  $("ol.example").sortable()
	})

</script>
<script>
$(function () {
    $('form.create-group-form').ajaxForm({
        url: FA_source() + '?t=group&a=create',
        
        beforeSend: function() {
            $('form.create-group-form')
                .find('button')
                    .removeClass()
                    .text('<?php echo $lang['creating']; ?>...');
        },
        
        success: function(responseText) {
            
            if (responseText.status == 200) {
                window.location = responseText.url;
            }
            else {
                $('form.create-group-form')
                .find('button')
                    .addClass('active')
                    .text('<?php echo $lang['group_create_label']; ?>');
            }
        }
    });
});
</script>