<style type="text/css">


* {
  .border-radius(0) !important;
}

#field {
    margin-bottom:20px;
}
</style>

<div class="float-left span59">

    <form class="create-group-form" method="post" id="form">
        <div class="form-container">
            <div class="form-header"><?php echo $lang['polls_create_label']; ?></div>
            <div class="form-input-wrapper">
                <label class="float-left span20"><?php echo $lang['polls_name_label']; ?>:</label>
                
                <div class="input float-left span70">
                    <input type="text" value="" placeholder="<?php echo $lang['polls_name_label_plcaeholder']?>" data-placeholder="<?php echo $lang['group_name_textarea_label']; ?>" onkeyup="FA_generateUsername(this.value);" data-copy-to=".group-name-input">
                    
                    <input class="group-name-input" type="hidden" name="group_name">
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    <?php
                    echo $lang['about_label'];
                    ?>:
                </label>
                
                <div class="input float-left span70">
                    <textarea class="auto-grow-input" valign="top" name="group_about" placeholder="<?php echo $lang['polls_description_textarea_label']; ?>" data-placeholder="<?php echo $lang['group_description_textarea_label']; ?>"><?php echo $lang['group_description_textarea_label']; ?></textarea>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">Options(s):</label>
                
                <div class="input float-left span70">
                    <div id="field"><input autocomplete="off" class="input" id="field1" name="prof1" type="text" placeholder="Type something" data-items="8"/><button id="b1" class="btn add-more" type="button">+</button></div>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
               
                
                <div class="input float-left span70">
                    <input type="hidden" value="closed" name="group_privacy" valign="top">
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <button class="active">
                    <?php
                    echo $lang['polls_create_label'];
                    ?>
                </button>
                <div class="post-message" style="display: block;"></div>
                <div class="float-clear"></div>
            </div>
        </div>
    </form>
</div>

<div class="float-right span40">
    <div class="list-wrapper">
        <div class="list-header"><?php echo $lang['group_intro_header']; ?></div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list1_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list1_description']; ?>
        </div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list2_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list2_description']; ?>
        </div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list3_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list3_description']; ?>
        </div>
    </div>
</div>
<div class="float-clear"></div>

<script>
$(function () {
	//var form_data = $('#form').serialize();
    $('form.create-group-form').ajaxForm({
        url: FA_source() + '?t=polls&a=create',
        
        beforeSend: function() {
            $('form.create-group-form')
                .find('div.post-message')
                    .text('<?php echo $lang['creating']; ?>...');
        },
        
        success: function(responseText) {
            
            if (responseText.status == 200) {
                window.location = responseText.url;
            }
            else { alert(1);
                $('form.create-group-form')
                .find('div.post-message').html('Title, Options are required field');
            }
        }
    });
});

$(document).ready(function(){
    var next = 1;
    $(".add-more").click(function(e){
        e.preventDefault();
        var addto = "#field" + next;
        var addRemove = "#field" + (next);
        next = next + 1;
        var newIn = '<input autocomplete="off" class="input form-control" id="field' + next + '" name="field' + next + '" type="text">';
        var newInput = $(newIn);
        var removeBtn = '<button id="remove' + (next - 1) + '" class="btn btn-danger remove-me" >-</button></div><div id="field">';
        var removeButton = $(removeBtn);
        $(addto).after(newInput);
        $(addRemove).after(removeButton);
        $("#field" + next).attr('data-source',$(addto).attr('data-source'));
        $("#count").val(next);  
        
            $('.remove-me').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
            });
    });
    

    
});

</script>