<div class="page-margin"></div>

<!--<div class="float-left span50">
    <?php
/*    //echo FA_getPage('more/manage-pages');
    */?>
</div>-->

<div class="float-left span32">
    <?php
    echo FA_getPage('more/manage-galleries');
    ?>
</div>


<div class="float-left span32">
    <?php
    echo FA_getPage('more/manage-groups');
    ?>
</div>

<div class="float-left span32">
    <?php
    echo FA_getPage('more/manage-gangs');
    ?>
</div>
<div class="float-left span32">
    <?php
    echo FA_getPage('more/manage-polls');
    ?>
</div>



<div class="float-clear"></div>