<div class="list-wrapper">
    <div class="list-header">
        <div class="float-left">
            <?php echo $lang['manage_polls_header_label']; ?>
        </div>

        <div class="float-right">
            <a class="hover-line" href="<?php echo FA_smoothLink('index.php?tab1=create_polls'); ?>" data-href="?tab1=create_polls">
                <?php echo $lang['polls_create_label']; ?>
            </a>
        </div>

        <div class="float-clear"></div>
    </div>
    <?php
    if (($manages_groups_num = FA_countManagedGroups()) == 0) {
    ?>
    <div class="list-column">
        <?php echo $lang['no_managed_polls_label']; ?>.
    </div>
    <?php
    } else {
        foreach (FA_getManagedGroups() as $group) { ?>
    <div class="list-column">
        <a class="bold-500" href="<?php echo $group['url']; ?>" data-href="?tab1=timeline&id=<?php echo $group['username']; ?>">
            <?php echo $group['name']; ?>
        </a>
    </div>
    <?php
        }
    }
    ?>
</div>