
<div class="list-wrapper">
    <div class="list-header">
        <div class="float-left">
            <?php echo $lang['manage_galleries_header_label']; ?>
        </div>

        <div class="float-right">
        
        	<a class="hover-line" href="<?php echo FA_smoothLink('index.php?tab1=gallery&tab2=create'); ?>" data-href="?tab1=gallery&tab2=create">
        		<?php echo $lang['gallery_create_label']; ?>
        	</a>
            
        </div>

        <div class="float-clear"></div>
    </div>
    <?php
    
    $albums = FA_getAlbums($_SESSION['user_id']);
        
    if (empty($albums)) {
    ?>
    <div class="list-column">
        <?php echo $lang['no_managed_galleries_label']; ?>.
    </div>
    <?php
    } else {
        foreach ($albums as $album) {
    ?>
    <div class="list-column">
        <table border="0" width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td width="42px" align="left" valign="middle">
                <a href="<?php echo FA_smoothLink('index.php?tab1=gallery&tab2=' . $album['id']); ?>" data-href="index.php?tab1=gallery&tab2=<?php echo $album['id']; ?>">
                    <!-- <img width="36px" height="36px" class="radius3" src="<?php echo $page['avatar_url']; ?>" alt="<?php echo $album['name']; ?>"> -->
                    <img width="36px" height="36px" class="radius3" src="themes/lightblue/images/default-page-avatar.png">                    
                </a>
            </td>
            <td align="left" valign="middle">
                <a class="bold-500" href="<?php echo FA_smoothLink('index.php?tab1=gallery&tab2=' . $album['id']); ?>" data-href="index.php?tab1=gallery&tab2=<?php echo $album['id']; ?>">
                    <?php echo $album['name']; ?>
                </a>
            </td>
        </tr>
        </table>
    </div>
    <?php
        } // end of foreach ($albums as $album).
    } // end of else of if (empty($albums)).
    ?>
</div>